project:
  type: website
  render:
    - index.qmd
    - Projects.qmd
    - Publications.qmd
    - posters.qmd
    - material_docente.qmd
    - web.qmd


website:
  title: "Verónica Cruz-Alonso"
  description: "Web personal de Verónica Cruz-Alonso"
  site-url: https://VeruGHub.github.io/veroweb/
  repo-url: https://github.com/VeruGHub/veroweb
  # favicon: logo.png
  twitter-card: true
  #   creator: "@handle"
  #   site: "@handle"
  open-graph: true
  # google-analytics:
  #   tracking-id: "UA-XXXXXXXX"
  #   anonymize-ip: true
  # cookie-consent: true


  navbar:
    title: false
    right:
      - href: index.qmd
        text: Sobre mí
      - href: Projects.qmd
        text: Proyectos
      - href: Publications.qmd
        text: Publicaciones
      - href: posters.qmd
        text: Posters
      - href: material_docente.qmd
        text: Material docente
      - href: https://verughub.github.io/easyclimate/
        text: easyclimate
      - href: web.qmd
        text: Sobre este sitio

      # - icon: mastodon
      #   href: https://joinmastodon.org
      # - text: "{{< iconify fa6-brands bluesky title='BlueSky'>}}"
      #   href: https://bsky.app
      # - text: "{{< iconify fa6-brands x-twitter title='Twitter'>}}"
      #   href: https://x.com
      # - icon: github
      #   href: https://github.com
      # - icon: linkedin
      #   href: https://linkedin.com/
      # - text: "{{< iconify academicons google-scholar-square size=1.2em title='Scholar'>}}"
      #   href: https://scholar.google.com
      # - text: "{{< iconify fa6-brands orcid size=1.2em title='ORCID' >}}"
      #   href: https://orcid.org/
      # - icon: twitter
      #   href: https://twitter.com

  page-footer:
    background: "#CBBAB5"
    right: "Hecho con Quarto"
  # back-to-top-navigation: true


lang: es

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

execute:
  freeze: auto  # re-render only when source changes



